# Form implementation generated from reading ui file '.\Views\smartOff.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Views.stateCabinet import *
import sys



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 760)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.563, y1:0.119318, x2:0.619, y2:1, stop:0 rgba(0, 69, 255, 255), stop:1 rgba(52, 139, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infotButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton.setGeometry(QtCore.QRect(130, 110, 300, 241))
        self.infotButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton.setObjectName("infotButton")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(420, 20, 301, 61))
        self.title.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.infotButton_2 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton_2.setGeometry(QtCore.QRect(550, 110, 300, 241))
        self.infotButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton_2.setObjectName("infotButton_2")
        self.infotButton_3 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton_3.setGeometry(QtCore.QRect(130, 450, 300, 241))
        self.infotButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton_3.setObjectName("infotButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        # #########################################




        # #########################################





        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infotButton.setText(_translate("MainWindow", "Освещение"))
        self.title.setText(_translate("MainWindow", "Система умный кабинет"))
        self.infotButton_2.setText(_translate("MainWindow", "Система безопасности"))
        self.infotButton_3.setText(_translate("MainWindow", "Управление климотом"))
    def radio_button(self):
        cab_y = 20
        cab = Cabinet_Controller()
        self.list_radiobutton = []
        for cabinet in cab.get():
            # name_button = f"radioButtonCabinet_{cabinet.id}"
            # self.name = f"radioButtonCabinet{cabinet.id}"
            self.name = QtWidgets.QRadioButton(f'{cabinet.id}',parent=self.centralwidget)
            self.name.cabinet = cabinet.name
            self.name.setGeometry(QtCore.QRect(900, cab_y, 201, 21))
            # self.name.setObjectName(name_button)
            _translate = QtCore.QCoreApplication.translate
            self.name.setText(_translate("TestHomeWindow", f"Выберите кабинет номер {cabinet.name}"))
            self.list_radiobutton.append(self.name)
            cab_y += 23
    def onClicked(self):
        for button in self.list_radiobutton:
            if button.isChecked():
                cabinet_name = button.cabinet
        global outpInformationWindow
        # 4 скопированы из stateCABINET
        outpInformationWindow = QtWidgets.QMainWindow()
        ui = Ui_outpInformationWindow(cabinet_name)
        ui.setupUi(outpInformationWindow)
        def test():
            print('!!!!!')
            ui.show_state_lamps()
        ui.pushButtonAll.clicked.connect(test)
        outpInformationWindow.show()



# метод перехода в окно сосояния ЛАМП
def open_windows(self):

    global outpInformationWindow
    # 4 скопированы из stateCABINET
    outpInformationWindow = QtWidgets.QMainWindow()
    ui = Ui_outpInformationWindow('207Т')
    ui.setupUi(outpInformationWindow)

    # ui.clicked()
    def test():
        print('!!!!!')
        ui.show_state_lamps()


    print(ui.name_cabinet)
    ui.pushButtonAll.clicked.connect(test)
    outpInformationWindow.show()
    MainWindow.close()



    # sys.exit(app.exec())

# import sys
# app = QtWidgets.QApplication(sys.argv)
# MainWindow = QtWidgets.QMainWindow()
# ui = Ui_MainWindow()
# ui.setupUi(MainWindow)
#
# ui.infotButton.clicked.connect(open_windows)
# MainWindow.show()
# sys.exit(app.exec())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    sys._excepthook = sys.excepthook
    ui.radio_button()

    def my_exeption_hook(exctype, value, traceback):
        print(exctype, value, traceback)

        sys._excepthook(exctype, value, traceback)
        sys.exit(1)


    sys.excepthook = my_exeption_hook

    try:
        sys.exit(app.exec_())

    except Exception:
        # переход в оно стсояния ЛАМП
        ui.infotButton.clicked.connect(ui.onClicked)

    MainWindow.show()
    sys.exit(app.exec())
