# Form implementation generated from reading ui file '.\Views\cameras.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Views.editCamera import *

class Ui_camerasWindow(object):
    def setupUi(self, camerasWindow):
        camerasWindow.setObjectName("camerasWindow")
        camerasWindow.resize(1134, 760)
        camerasWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.563, y1:0.119318, x2:0.619, y2:1, stop:0 rgba(0, 69, 255, 255), stop:1 rgba(52, 139, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=camerasWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infotButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton.setGeometry(QtCore.QRect(130, 150, 371, 81))
        self.infotButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton.setObjectName("infotButton")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(420, 20, 301, 61))
        self.title.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        camerasWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(camerasWindow)
        QtCore.QMetaObject.connectSlotsByName(camerasWindow)

    def retranslateUi(self, camerasWindow):
        _translate = QtCore.QCoreApplication.translate
        camerasWindow.setWindowTitle(_translate("camerasWindow", "MainWindow"))
        self.infotButton.setText(_translate("camerasWindow", "Управление камерами"))
        self.title.setText(_translate("camerasWindow", "Камеры"))






# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     camerasWindow = QtWidgets.QMainWindow()
#     ui = Ui_camerasWindow()
#
#     ui.setupUi(camerasWindow)
#
#     camerasWindow.show()
#     sys.exit(app.exec())
