# Form implementation generated from reading ui file '.\Views\editCamera.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controllers.Camera_Controller import *

class Ui_editCameraWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 643)
        MainWindow.setStyleSheet("background-color: rgb(255, 20, 3);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infotButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton.setGeometry(QtCore.QRect(40, 530, 251, 71))
        self.infotButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton.setObjectName("infotButton")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(560, 30, 281, 61))
        self.title.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(1010, 140, 241, 41))
        self.addButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.addButton.setObjectName("addButton")
        self.textAddName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textAddName.setGeometry(QtCore.QRect(30, 140, 291, 41))
        self.textAddName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textAddName.setObjectName("textAddName")
        self.textAddLink = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textAddLink.setGeometry(QtCore.QRect(370, 140, 291, 41))
        self.textAddLink.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textAddLink.setObjectName("textAddLink")
        self.textUpadateNewName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateNewName.setGeometry(QtCore.QRect(370, 230, 291, 41))
        self.textUpadateNewName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateNewName.setObjectName("textUpadateNewName")
        self.textUpadateOldName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateOldName.setGeometry(QtCore.QRect(30, 230, 291, 41))
        self.textUpadateOldName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateOldName.setObjectName("textUpadateOldName")
        self.updateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(1010, 230, 241, 41))
        self.updateButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.updateButton.setObjectName("updateButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(1010, 400, 241, 41))
        self.deleteButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.deleteButton.setObjectName("deleteButton")
        self.textDeleteName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textDeleteName.setGeometry(QtCore.QRect(30, 410, 291, 41))
        self.textDeleteName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textDeleteName.setObjectName("textDeleteName")
        self.textAddCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textAddCabinet.setGeometry(QtCore.QRect(700, 140, 281, 41))
        self.textAddCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textAddCabinet.setObjectName("textAddCabinet")
        self.updateButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton_2.setGeometry(QtCore.QRect(1010, 320, 241, 41))
        self.updateButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.updateButton_2.setObjectName("updateButton_2")
        self.textName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textName.setGeometry(QtCore.QRect(30, 320, 291, 41))
        self.textName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textName.setObjectName("textName")
        self.textNewLink = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textNewLink.setGeometry(QtCore.QRect(370, 320, 291, 41))
        self.textNewLink.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textNewLink.setObjectName("textNewLink")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infotButton.setText(_translate("MainWindow", "Главная камеры"))
        self.title.setText(_translate("MainWindow", "НАЗВАНИЕ Окна"))
        self.addButton.setText(_translate("MainWindow", "Добавить камеру"))
        self.textAddName.setPlaceholderText(_translate("MainWindow", "Название камеры"))
        self.textAddLink.setPlaceholderText(_translate("MainWindow", "ссылка"))
        self.textUpadateNewName.setPlaceholderText(_translate("MainWindow", "Введите новое название"))
        self.textUpadateOldName.setPlaceholderText(_translate("MainWindow", "Введите старое название"))
        self.updateButton.setText(_translate("MainWindow", "Обновить имя"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить камеру"))
        self.textDeleteName.setPlaceholderText(_translate("MainWindow", "Введите название камеры"))
        self.textAddCabinet.setPlaceholderText(_translate("MainWindow", "Номер кабинета"))
        self.updateButton_2.setText(_translate("MainWindow", "Обновить ссылку"))
        self.textName.setPlaceholderText(_translate("MainWindow", "Введите название камеры"))
        self.textNewLink.setPlaceholderText(_translate("MainWindow", "Введите новая ссылка"))

#     добавть запись
    def add(self):
        name = self.textAddName.toPlainText()
        link = self.textAddLink.toPlainText()
        cabinet = self.textAddCabinet.toPlainText()
        camera = Camera_Controller()
        camera.add(name,link,cabinet)
        self.textAddName.setText('')
        self.textAddLink.setText('')
        self.textAddCabinet.setText('')

    # обновить
    def update_name(self):
        old_name = self.textUpadateOldName.toPlainText()
        new_name = self.textUpadateNewName.toPlainText()
        camera=Camera_Controller()
        camera.update_name(old_name,new_name)
        self.textUpadateOldName.setText('')
        self.textUpadateNewName.setText('')

    def update_link(self):
        name = self.textName.toPlainText()
        link = self.textAddLink.toPlainText()
        camera = Camera_Controller()
        camera.update_link(name,link)
        self.textName.setText('')
        self.textAddLink.setText('')

#         удаление
    def delete(self):
        name = self.textDeleteName.toPlainText()
        camera = Camera_Controller()
        camera.delete(name)
        self.textDeleteName.setText('')
    def clicked_button(self):
        self.addButton.clicked.connect(self.add)
        self.updateButton.clicked.connect(self.update_name)
        self.updateButton_2.clicked.connect(self.update_link)
        self.deleteButton.clicked.connect(self.delete)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_editCameraWindow()
    ui.setupUi(MainWindow)
    ui.clicked_button()
    # # кнопка с событием нажатие и выполнения добавления
    # ui.addButton.clicked.connect(ui.add)
    # # кнопка обновить имя
    # ui.updateButton.clicked.connect(ui.update_name)
    # # кнопка обновить имя
    # ui.updateButton_2.clicked.connect(ui.update_link)
    # # удаление
    # ui.deleteButton.clicked.connect(ui.delete)
    camera = Camera_Controller()
    def print_cameras():
        for row in camera.get():
            print(row.id, row.name,row.link,row.cabinet_id.name)

    print_cameras()
    MainWindow.show()
    sys.exit(app.exec())
