# Form implementation generated from reading ui file '.\Views\editCabinet.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controllers.Cabinet_Controller import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 739)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.cabinetButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.cabinetButton.setGeometry(QtCore.QRect(50, 630, 251, 71))
        self.cabinetButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.cabinetButton.setObjectName("cabinetButton")

        # создание кнопки вручную

        self.homeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(350,630,251,71))
        self.homeButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.homeButton.setObjectName("homeButton")

        self.titleCabinet = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleCabinet.setGeometry(QtCore.QRect(360, 30, 281, 61))
        self.titleCabinet.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.titleCabinet.setObjectName("titleCabinet")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(740, 140, 241, 41))
        self.addButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.addButton.setObjectName("addButton")
        self.textEditNameCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditNameCabinet.setGeometry(QtCore.QRect(30, 140, 291, 41))
        self.textEditNameCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textEditNameCabinet.setObjectName("textEditNameCabinet")
        self.textEditDepartamentCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditDepartamentCabinet.setGeometry(QtCore.QRect(390, 140, 291, 41))
        self.textEditDepartamentCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textEditDepartamentCabinet.setObjectName("textEditDepartamentCabinet")
        self.textUpadateNewNameCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateNewNameCabinet.setGeometry(QtCore.QRect(390, 230, 291, 41))
        self.textUpadateNewNameCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateNewNameCabinet.setObjectName("textUpadateNewNameCabinet")
        self.textUpadateOldNameCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateOldNameCabinet.setGeometry(QtCore.QRect(30, 230, 291, 41))
        self.textUpadateOldNameCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateOldNameCabinet.setObjectName("textUpadateOldNameCabinet")
        self.updateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(740, 230, 241, 41))
        self.updateButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.updateButton.setObjectName("updateButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(740, 320, 241, 41))
        self.deleteButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.deleteButton.setObjectName("deleteButton")
        self.textDeleteNameCabinet = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textDeleteNameCabinet.setGeometry(QtCore.QRect(30, 320, 291, 41))
        self.textDeleteNameCabinet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textDeleteNameCabinet.setObjectName("textDeleteNameCabinet")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cabinetButton.setText(_translate("MainWindow", "Кабинет"))
        self.homeButton.setText(_translate("MainWindow", "Вернуться в стартовое окно"))
        self.titleCabinet.setText(_translate("MainWindow", "Изменение кабинетов"))
        self.addButton.setText(_translate("MainWindow", "Добавить кабинет"))
        self.textEditNameCabinet.setPlaceholderText(_translate("MainWindow", "Введите название кабинета"))
        self.textEditDepartamentCabinet.setPlaceholderText(_translate("MainWindow", "Введите название отделения"))
        self.textUpadateNewNameCabinet.setPlaceholderText(_translate("MainWindow", "Введите новое название"))
        self.textUpadateOldNameCabinet.setPlaceholderText(_translate("MainWindow", "Введите старое название"))
        self.updateButton.setText(_translate("MainWindow", "Обновит кабинет"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить кабинет"))
        self.textDeleteNameCabinet.setPlaceholderText(_translate("MainWindow", "Введите название кабинета"))
    def show(self):
        cab = Cabinet_Controller()
        for row in cab.get():
            print(row)

if __name__ == "__main__":
    import sys

    sys._excepthook = sys.excepthook

    def my_exeption_hook(exctype,value,traceback):

        print(exctype,value,traceback)

        sys._excepthook(exctype,value,traceback)
        sys.exit(1)

    sys.excepthook = my_exeption_hook

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    cabinet = Cabinet_Controller()
    def add():
        cab = ui.textEditNameCabinet.toPlainText()
        departament = ui.textEditDepartamentCabinet.toPlainText()
        cabinet.add_value(cab, departament)
        # Очистить окна input от текста
        ui.textEditNameCabinet.setText('')
        ui.textEditDepartamentCabinet.setText('')
        # for element in cabinet.get():
        #     print(element.name)

        for e in cabinet.last_row():
            print(e.name)


    # Обновить
    def update():
        new_name =ui.textUpadateNewNameCabinet.toPlainText()
        old_name = ui.textUpadateOldNameCabinet.toPlainText()
        cabinet.update_name(new_name,old_name)
        ui.textUpadateNewNameCabinet.setPlainText('')
        ui.textUpadateOldNameCabinet.setPlainText('')

    def delete():
        name = ui.textDeleteNameCabinet.toPlainText()

        cabinet.delete_field(name)
        ui.textDeleteNameCabinet.setText('')


    try:
        sys.exit(app.exec_())

    except:
        ui.addButton.clicked.connect(add)
        ui.updateButton.clicked.connect(update)
        ui.deleteButton.clicked.connect(delete)
        print("Всё ОК!")

    ui.show()






    MainWindow.show()
    sys.exit(app.exec())
