# Form implementation generated from reading ui file '.\Views\editCondicioner.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controllers.Air_conditioners_Controller import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 739)
        MainWindow.setStyleSheet("background-color: rgb(41, 154, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infotButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.infotButton.setGeometry(QtCore.QRect(30, 650, 251, 71))
        self.infotButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.infotButton.setObjectName("infotButton")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(360, 30, 281, 61))
        self.title.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(740, 140, 241, 41))
        self.addButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.addButton.setObjectName("addButton")
        self.textEditName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditName.setGeometry(QtCore.QRect(30, 140, 291, 41))
        self.textEditName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textEditName.setObjectName("textEditName")
        self.textEditDepartament = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditDepartament.setGeometry(QtCore.QRect(390, 140, 291, 41))
        self.textEditDepartament.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textEditDepartament.setObjectName("textEditDepartament")
        self.textUpadateNewName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateNewName.setGeometry(QtCore.QRect(390, 230, 291, 41))
        self.textUpadateNewName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateNewName.setObjectName("textUpadateNewName")
        self.textUpadateOldName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUpadateOldName.setGeometry(QtCore.QRect(30, 230, 291, 41))
        self.textUpadateOldName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textUpadateOldName.setObjectName("textUpadateOldName")
        self.updateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(740, 230, 241, 41))
        self.updateButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.updateButton.setObjectName("updateButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(740, 320, 241, 41))
        self.deleteButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.534, y1:0.199, x2:1, y2:1, stop:0.0564972 rgba(72, 124, 221, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:3px;")
        self.deleteButton.setObjectName("deleteButton")
        self.textDeleteName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textDeleteName.setGeometry(QtCore.QRect(30, 320, 291, 41))
        self.textDeleteName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"border-radius:3px;\n"
"padding:2px;\n"
"placeholderTetx:\"Введите название кабинета\";")
        self.textDeleteName.setObjectName("textDeleteName")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infotButton.setText(_translate("MainWindow", "Кабинет"))
        self.title.setText(_translate("MainWindow", "Изменение Окна"))
        self.addButton.setText(_translate("MainWindow", "Добавить кондиционер"))
        self.textEditName.setPlaceholderText(_translate("MainWindow", "Введите название кондиционера"))
        self.textEditDepartament.setPlaceholderText(_translate("MainWindow", "Введите название кабинета"))
        self.textUpadateNewName.setPlaceholderText(_translate("MainWindow", "Введите новое название"))
        self.textUpadateOldName.setPlaceholderText(_translate("MainWindow", "Введите старое название"))
        self.updateButton.setText(_translate("MainWindow", "Обновит кондиционер"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить кондиционер"))
        self.textDeleteName.setPlaceholderText(_translate("MainWindow", "Введите название кондиционера"))

#     добавить запись
    def add(self):
        name = self.textEditName.toPlainText()
        cabinet = self.textEditDepartament.toPlainText()
        condicioner = Air_conditioners_Controller()
        condicioner.add_value(name,cabinet)
        self.textEditName.setText('')
        self.textEditDepartament.setText('')

    def update(self):
        old_name = self.textUpadateOldName.toPlainText()
        new_name = self.textUpadateNewName.toPlainText()
        conditioner.update(old_name,new_name)
        self.textUpadateOldName.setText('')
        self.textUpadateNewName.setText('')

    def delete(self):
        name = self.textDeleteName.toPlainText()
        conditioner.delete(name)
        self.textDeleteName.setPlainText('')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    conditioner = Air_conditioners_Controller()
     # Изменить заголовок ОКНА
    ui.title.setText(Air_conditioners.window_name)
    # Вешаем на событие кнопки функцию add
    for el in conditioner.get():
        print(el.name,el.cabinet_id.name, el.state)
    ui.addButton.clicked.connect(ui.add)
    ui.updateButton.clicked.connect(ui.update)
    ui.deleteButton.clicked.connect(ui.delete)





    MainWindow.show()
    sys.exit(app.exec())

