# Form implementation generated from reading ui file '.\Views\stateCabinet.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controllers.Camera_Controller import *
from Controllers.Cabinet_Controller import *
from Controllers.LampController import *

class Ui_outpInformationWindow(object):
    # конструктор
    def __init__(self,name_cabinet):
        self.name_cabinet = name_cabinet
    # Поля передающие значение - ВЫБРАННЫЙ КАБИНЕТ
    cabinet = Cabinet_Controller()

    # name_cabinet = '215Т'

    flag = False

    def setupUi(self, outpInformationWindow):
        outpInformationWindow.setObjectName("outpInformationWindow")
        outpInformationWindow.resize(1126, 738)
        outpInformationWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.512, y1:0, x2:0.505318, y2:0.603, stop:0 rgba(15, 58, 250, 255), stop:1 rgba(10, 137, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=outpInformationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleWindow = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleWindow.setGeometry(QtCore.QRect(290, 20, 511, 51))
        self.titleWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"MS Shell Dlg 2\";")
        self.titleWindow.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleWindow.setObjectName("titleWindow")
        self.nameCabinet = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameCabinet.setGeometry(QtCore.QRect(290, 90, 511, 51))
        self.nameCabinet.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.nameCabinet.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameCabinet.setObjectName("nameCabinet")

        #################### Освещение ###########################
        self.titleLamps = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLamps.setGeometry(QtCore.QRect(10, 170, 311, 51))
        self.titleLamps.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.titleLamps.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLamps.setObjectName("titleLamps")
        self.textBrowserLamps = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowserLamps.setGeometry(QtCore.QRect(10, 240, 311, 191))
        self.textBrowserLamps.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.textBrowserLamps.setObjectName("textBrowserLamps")

        self.pushButtonAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAll.setGeometry(QtCore.QRect(10, 460, 311, 41))
        self.pushButtonAll.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonAll.setObjectName("pushButtonAll")

        self.pushButtonA1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonA1.setGeometry(QtCore.QRect(10, 530, 311, 41))
        self.pushButtonA1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonA1.setObjectName("pushButtonA1")

        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(10, 600, 311, 41))
        self.pushButton2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton2.setObjectName("pushButton2")
        #################### Конец Освещение ###########################

        ################### Камеры  ###################

        self.titleCameras = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleCameras.setGeometry(QtCore.QRect(410, 170, 311, 51))
        self.titleCameras.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 18pt \"MS Shell Dlg 2\";")
        self.titleCameras.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleCameras.setObjectName("titleCameras")
        self.textBrowserCameras = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowserCameras.setGeometry(QtCore.QRect(410, 240, 311, 191))
        self.textBrowserCameras.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "font: 12pt \"MS Shell Dlg 2\";")
        self.textBrowserCameras.setObjectName("textBrowserCameras")

        self.pushButtonAllCameras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAllCameras.setGeometry(QtCore.QRect(410, 460, 311, 41))
        self.pushButtonAllCameras.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                "font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonAllCameras.setObjectName("pushButtonAll")

        self.pushButtonSection1Cameras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSection1Cameras.setGeometry(QtCore.QRect(410, 530, 311, 41))
        self.pushButtonSection1Cameras.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                     "font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonSection1Cameras.setObjectName("pushButtonSection1Cameras")

        self.pushButtonSection2Cameras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSection2Cameras.setGeometry(QtCore.QRect(410, 600, 311, 41))
        self.pushButtonSection2Cameras.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                     "font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonSection2Cameras.setObjectName("pushButtonSection2Cameras")

        ################### конец Камеры  ###################

        outpInformationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=outpInformationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        outpInformationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=outpInformationWindow)
        self.statusbar.setObjectName("statusbar")
        outpInformationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(outpInformationWindow)
        # надпись на кнопке вкл/выкл
        self.text_button_all()
        self.text_button_section_1()
        self.text_buuton_section_2()







        ###################

        self.clicked()
        self.show_state_lamps()
        ############################
        QtCore.QMetaObject.connectSlotsByName(outpInformationWindow)

    def retranslateUi(self, outpInformationWindow):

        _translate = QtCore.QCoreApplication.translate
        outpInformationWindow.setWindowTitle(_translate("outpInformationWindow", "MainWindow"))
        self.titleWindow.setText(_translate("outpInformationWindow", "Сотояние кабинета"))
        self.nameCabinet.setText(_translate("outpInformationWindow", f"Кабинет номер: {self.name_cabinet}"))
        self.titleLamps.setText(_translate("outpInformationWindow", "Освещение"))
        self.pushButtonAll.setText(_translate("outpInformationWindow", "PushButton"))
        self.pushButtonA1.setText(_translate("outpInformationWindow", "PushButton"))
        self.pushButton2.setText(_translate("outpInformationWindow", "PushButton"))

        ################### конец Камеры  ###################

        self.titleCameras.setText(_translate("outpInformationWindow", "Освещение"))
        self.pushButtonAllCameras.setText(_translate("outpInformationWindow", "PushButton"))
        self.pushButtonSection1Cameras.setText(_translate("outpInformationWindow", "PushButton"))
        self.pushButtonSection2Cameras.setText(_translate("outpInformationWindow", "PushButton"))
        ################### Камеры  ###################

    # метод вывода информации о состоянии ЛАМП
    def show_state_lamps(self):
        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id = cabinet.show_id(self.name_cabinet)
        lamps = lamp.show_lamps(cabinet_id)
        # Строка, которая будет предана в textBrowserLamps
        str = ''
        for row in lamps:
            str += f"Лампа {row.id}, секция {row.seсtion_id.name} - состояние {row.state} \n"
        self.textBrowserLamps.setText(str)
        return str




    #метод изменения состояния ЛАМП

    def in_on_all_lamps(self):

        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id = cabinet.show_id(self.name_cabinet)

        if not lamp.state_of_lamps(cabinet_id):
            self.pushButtonAll.setText('Выключить все лампы')
        else:
            self.pushButtonAll.setText('Включить все лампы')

        lamp.power_off_all(cabinet_id,not lamp.state_of_lamps(cabinet_id))
        self.show_state_lamps()

    # метод вкл/выкл ламп первой секции
    def in_on_setion_1(self):

        lamp = LampController()
        cabinet = Cabinet_Controller()

        cabinet_id = cabinet.show_id(self.name_cabinet)
        setion_id = lamp.list_section_id(cabinet_id)[0] # это первая секция кабинета
        if not lamp.state_of_lamps_section(cabinet_id,setion_id):
            self.pushButtonA1.setText('Выключить секцию ламп')
        else:
            self.pushButtonA1.setText('Включить секцию ламп')

        lamp.power_off_section(cabinet_id,not lamp.state_of_lamps_section(cabinet_id,setion_id),setion_id)
        self.show_state_lamps()

    def in_on_setion_2(self):
        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id =cabinet.show_id(self.name_cabinet)
        section_id = lamp.list_section_id(cabinet_id)[1] # это вторая секция

        if not lamp.state_of_lamps_section(cabinet_id,section_id):
            self.pushButton2.setText('Выключить секцию 2')
        else:
            self.pushButton2.setText('Включить секцию 2')

        lamp.power_off_section(cabinet_id,not lamp.state_of_lamps_section(cabinet_id,section_id),section_id)

        self.show_state_lamps()







    # Надпись на кнопке включения/выключения всех ламп
    def text_button_all(self):
        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id = cabinet.show_id(self.name_cabinet)
        if lamp.state_of_lamps(cabinet_id):
            self.pushButtonAll.setText('Выключить все лампы')
        else:
            self.pushButtonAll.setText('Включить все лампы')

    def text_button_section_1(self):
        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id = cabinet.show_id(self.name_cabinet)
        if lamp.state_of_lamps_section(1,cabinet_id):
            self.pushButtonA1.setText('Выключить секцию ламп')
        else:
            self.pushButtonA1.setText('Включить секцию ламп')

    def text_buuton_section_2(self):
        lamp = LampController()
        cabinet = Cabinet_Controller()
        cabinet_id = cabinet.show_id(self.name_cabinet)

        if lamp.state_of_lamps_section(2,cabinet_id):
            self.pushButton2.setText('Выключить секцию 2')
        else:
            self.pushButton2.setText('Включить секцию 2')
    #         сохраняем стотояние кнопки


    def clicked(self):
        self.pushButtonAll.clicked.connect(self.in_on_all_lamps)
        self.pushButtonA1.clicked.connect(self.in_on_setion_1)
        self.pushButton2.clicked.connect(self.in_on_setion_2)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    outpInformationWindow = QtWidgets.QMainWindow()
    ui = Ui_outpInformationWindow('215Т')
    ui.setupUi(outpInformationWindow)




    outpInformationWindow.show()
    sys.exit(app.exec())
