# Form implementation generated from reading ui file '.\Views\testCondicioner.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controllers.Air_conditioners_Controller import *
from Controllers.ConditionController import *
class Ui_condicionerWindow(object):
    cabinet = Cabinet_Controller()
    name_cabinet = cabinet.show('215Т').name
    def setupUi(self, condicionerWindow):
        condicionerWindow.setObjectName("condicionerWindow")
        condicionerWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=condicionerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 440, 271, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.labelInformation = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelInformation.setGeometry(QtCore.QRect(50, 360, 281, 31))
        self.labelInformation.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelInformation.setObjectName("labelInformation")
        condicionerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=condicionerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        condicionerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=condicionerWindow)
        self.statusbar.setObjectName("statusbar")
        condicionerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(condicionerWindow)
        QtCore.QMetaObject.connectSlotsByName(condicionerWindow)

    def retranslateUi(self, condicionerWindow):
        _translate = QtCore.QCoreApplication.translate
        condicionerWindow.setWindowTitle(_translate("condicionerWindow", "MainWindow"))
        self.labelInformation.setText(_translate("condicionerWindow", "0"))

    def slider(self):

        self.horizontalSlider.valueChanged.connect(self.slider_it)

    def slider_it(self,value):
        cond = ConditionController()
        # value = cond.position(value)
        self.labelInformation.setText(str(value))
        print(value)

if __name__ == "__main__":
    cond = Air_conditioners_Controller()
    import sys
    app = QtWidgets.QApplication(sys.argv)
    condicionerWindow = QtWidgets.QMainWindow()
    ui = Ui_condicionerWindow()
    ui.setupUi(condicionerWindow)
    ui.slider()

    # ui.horizontalSlider.valueChanged.connect(ui.slider_it)
    # print(cond.show_state('215T-1'))
    condicionerWindow.show()
    sys.exit(app.exec())
