# Form implementation generated from reading ui file '.\Vews\LampView.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys,Vews.Images.Lamps.images

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 657)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(10, 181, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(850, 0, 201, 181))
        self.widget.setStyleSheet("image: url(:/img/lamp-charge-svgrepo-com.svg);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 451, 121))
        self.label.setStyleSheet("font:28pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(120, 160, 701, 71))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 231, 21))
        self.label_2.setObjectName("label_2")
        self.information_lamps = QtWidgets.QLabel(parent=self.widget_2)
        self.information_lamps.setGeometry(QtCore.QRect(20, 40, 201, 16))
        self.information_lamps.setText("")
        self.information_lamps.setObjectName("information_lamps")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 300, 241, 51))
        self.label_3.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"padding:5px\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 300, 241, 51))
        self.label_4.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"padding:5px\n"
"")
        self.label_4.setObjectName("label_4")
        self.onSection_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.onSection_1.setGeometry(QtCore.QRect(180, 460, 31, 31))
        self.onSection_1.setStyleSheet("image: url(:/Images/power-button-svgrepo-com.svg);\n"
"background-color: rgb(255, 255, 255);")
        self.onSection_1.setObjectName("onSection_1")
        self.offSection_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.offSection_1.setGeometry(QtCore.QRect(330, 460, 31, 31))
        self.offSection_1.setStyleSheet("image: url(:/Images/power-button-svgrepo-com.svg);\n"
"background-color: rgb(255, 255, 255);")
        self.offSection_1.setObjectName("offSection_1")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(320, 390, 51, 51))
        self.widget_4.setStyleSheet("image: url(:/img/power-button-svgrepo-com-red.svg);")
        self.widget_4.setObjectName("widget_4")
        self.offSection_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.offSection_2.setGeometry(QtCore.QRect(840, 450, 31, 31))
        self.offSection_2.setStyleSheet("image: url(:/Images/power-button-svgrepo-com.svg);\n"
"background-color: rgb(255, 255, 255);")
        self.offSection_2.setObjectName("offSection_2")
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(170, 380, 51, 51))
        self.widget_6.setStyleSheet("image: url(:/img/power-button-svgrepo-com.svg);")
        self.widget_6.setObjectName("widget_6")
        self.offSection_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.offSection_3.setGeometry(QtCore.QRect(690, 450, 31, 31))
        self.offSection_3.setStyleSheet("image: url(:/Images/power-button-svgrepo-com.svg);\n"
"background-color: rgb(255, 255, 255);")
        self.offSection_3.setObjectName("offSection_3")
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(830, 380, 51, 51))
        self.widget_5.setStyleSheet("image: url(:/img/power-button-svgrepo-com-red.svg);")
        self.widget_5.setObjectName("widget_5")
        self.widget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(680, 380, 51, 51))
        self.widget_7.setStyleSheet("image: url(:/img/power-button-svgrepo-com.svg);")
        self.widget_7.setObjectName("widget_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Овещение кабинета 215Т"))
        self.label_2.setText(_translate("MainWindow", "Информация об освещении"))
        self.label_3.setText(_translate("MainWindow", "Секция 1"))
        self.label_4.setText(_translate("MainWindow", "Секция 2"))
        self.onSection_1.setText(_translate("MainWindow", "Вкл"))
        self.offSection_1.setText(_translate("MainWindow", "Выкл"))
        self.offSection_2.setText(_translate("MainWindow", "Выкл"))
        self.offSection_3.setText(_translate("MainWindow", "Вкл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
